### ISSUE TITLE
Compiler / Linker issues on iOS 64bit simulator.

### ISSUE THREAD

**Issue by edkimmel** [cppformat/cppformat#88] opened 2015-01-05 16:19 UTC
Two part issue, and it's looking more like a compiler issue than anything. Occurs when trying to use  sprintf (any possibly any of the other surrounding macro-generated methods) with an empty va_list.

1) Compiler error
cppformat/format.h:2418:1: Calling a private constructor of class 'fmt::internal::MakeValue<char>'

So going against the comments, I changed the constructors to public. It then makes it to the linker phase, where it gives another error

2) Linker error

  "fmt::internal::MakeValue<char>::MakeValue<__va_list_tag>(__va_list_tag const*)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > fmt::sprintf<__va_list_tag [1]>(fmt::BasicStringRef<char>, __va_list_tag const (&) [1])

This is where I'm not template-savvy enough to go any further. Something about different templates on the left and right side of the :: seems wrong.

A solution I have for now is to keep the constructors as private and just undefine FMT_USE_VARIADIC_TEMPLATES.

**Comment by vitaut** [comment] 2015-01-06 15:02
Thanks for the bug report. Just to clarify, do you get an error for the code like this:
```
fmt::sprintf("test");
```

Also what compiler version and flags do you use?

**Comment by vitaut** [comment] 2015-01-23 15:18
I couldn't reproduce this with Xcode version 5.1.1, closing for now. Feel free to reopen with additional information how to reproduce this.

**Comment by edkimmel** [comment] 2015-01-23 21:53
Using Xcode 6.1.1, ios8 sdk.

Code is the following. There will only be an error when the va_list is empty.

    void Logger::Alert(const char* format, ...)
    {
        va_list args;
        va_start(args, format);
        
        std::string message = fmt::sprintf(format, args);
        va_end(args);
       ...
    }

**Comment by vitaut** [comment] 2015-01-23 22:03
Thanks, I'll look into it.

**Comment by vitaut** [comment] 2015-01-28 16:19
OK, I see what is going on here. The `fmt::sprintf` function accepts a list of arguments rather than a `va_list` object, so the error is expected. To fix this, you should wrap the call to `fmt::sprintf` in a variadic function or use `FMT_VARIADIC` as described in http://cppformat.readthedocs.org/en/stable/reference.html#utilities:

```
class Logger {
  ...
  void Alert(const char* format, fmt::ArgList args);
  FMT_VARIADIC(void, Alert, const char *)
};

void Logger::Alert(const char* format, fmt::ArgList args)
{
    std::string message = fmt::sprintf(format, args);
   ...
}
```
This is much safer than using varargs.

**Closed by vitaut** 2015-01-28 16:19 UTC

**Comment by edkimmel** [comment] 2015-02-12 03:27
Thanks a ton.
