### ISSUE TITLE
CenterAlign test failure

### ISSUE THREAD

**Issue by dean0x7d** [cppformat/cppformat#242] opened 2015-12-05 22:59 UTC
After checking out e7f4566dd4771ca790872b9ddc67165623103386, the `FormatterTest.CenterAlign` test fails on Apple Clang 7.0.0:
```
3: cppformat/test/format-test.cc:723: Failure
3: Value of: format("{0:^6}", -42.0)
3:   Actual: " ---  "
3: Expected: " -42  "
3: cppformat/test/format-test.cc:724: Failure
3: Value of: format("{0:^5}", -42.0l)
3:   Actual: " --- "
3: Expected: " -42 "
3: [  FAILED  ] FormatterTest.CenterAlign (0 ms)
```

I tracked down the bug to [this `std::uninitialized_copy`](https://github.com/cppformat/cppformat/blob/master/format.h#L2776): if I replace it with a regular `std::copy` the test passes.

My guess is that the compiler takes some liberties because both the source and destination use the same base pointer and the memory is assumed to be uninitialized. This could cause future problems with  `std::uninitialized_*` functions, depending on compiler optimizations.

I think the `copy` and `fill` functions should be simple enough to just implement directly in cppformat, without the overhead of parsing either `<algorithm>` or `<memory>`, or the potential problems with the `std::uninitialized_*` functions.

**Comment by vitaut** [comment] 2015-12-06 15:47
The problem is that the source and destination may overlap while `std::uninitialized_copy` may reasonably assume that they don't. Fixed in https://github.com/cppformat/cppformat/commit/98c1f76f24997aa60950096ea5e098891569d1d5. Thanks for reporting and tracking this down!

**Closed by vitaut** 2015-12-06 15:47 UTC

**Comment by vitaut** [comment] 2015-12-06 17:02
And AFAICS this is the only case where overlap is possible.
